align_assignment = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
always_for_in = true
conditional_to_if = true
for_in_replacement = "in"
format_docstrings = false
format_markdown = false
import_to_using = true
indent = 4
margin = 100
normalize_line_endings = "unix"
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
verbose = true
