name = "TulipaEnergyModel"
uuid = "5d7bd171-d18e-45a5-9111-f1f11ac5d04d"
authors = ["Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>", "Germán Morales-España <german.morales@tno.nl>", "Lauren Clisby <lauren.clisby@tno.nl>", "Ni Wang <ni.wang@tno.nl>", "Abel Soares Siqueira <abel.s.siqueira@gmail.com>", "Suvayu Ali <s.ali@esciencecenter.nl>", "Laurent Soucasse <l.soucasse@esciencecenter.nl>", "Greg Neustroev <G.Neustroev@tudelft.nl>"]
version = "0.10.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
DuckDB_jll = "2cbbab25-fc8b-58cf-88d4-687a02676033"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TulipaIO = "7b3808b7-0819-42d4-885c-978ba173db11"

[compat]
CSV = "0.10"
DataFrames = "1"
DuckDB = "0.10, ~1.0, 1"
DuckDB_jll = "0.10, ~1.0"
Graphs = "1.8"
HiGHS = "1"
JuMP = "1"
MathOptInterface = "1"
MetaGraphsNext = "0.6, 0.7"
OrderedCollections = "1"
SparseArrays = "1"
Statistics = "1"
TOML = "1"
TimerOutputs = "0.5"
TulipaIO = "0.1, 0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
