name = "TulipaEnergyModel"
uuid = "5d7bd171-d18e-45a5-9111-f1f11ac5d04d"
version = "0.20.1"
authors = [
  "Abel Soares Siqueira <abel.s.siqueira@gmail.com>",
  "Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>",
  "Germán Morales-España <german.morales@tno.nl>",
  "Grigory Neustroev <G.Neustroev@tudelft.nl>",
  "Juha Kiviluoma <Juha.Kiviluoma@vtt.fi>",
  "Lauren Clisby <lauren.clisby@tno.nl>",
  "Maaike Elgersma <m.b.elgersma@tudelft.nl>",
  "Ni Wang <ni.wang@tno.nl>",
  "Suvayu Ali <s.ali@esciencecenter.nl>",
  "Zhi Gao <z.gao1@uu.nl>",
]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TulipaIO = "7b3808b7-0819-42d4-885c-978ba173db11"

[compat]
CSV = "0.10"
DuckDB = "1"
HiGHS = "1"
JSON = "0.21.4, 1"
JuMP = "1"
MathOptInterface = "1"
OrderedCollections = "1"
ParametricOptInterface = "0.12.1, 0.14"
Statistics = "1"
TOML = "1"
TimerOutputs = "0.5"
TulipaIO = "0.5"
julia = "1.10"

[workspace]
projects = ["test", "docs", "benchmark"]
